version: '3'
services:
    wechat:
        build:
            context: ./wechat_server
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
        ports:
            - "5001:5001"
    web:
        build:
            context: ./web_server
        ports:
            - "3001:3001"
    backend:
        build:
            context: ./backend_server 
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
        ports:
            - "4040:4040"
    scraper:
        build:
            context: .
            dockerfile: ./house_listing_pipeline/scrape/Dockerfile
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
    filter:
        build:
            context: .
            dockerfile: ./house_listing_pipeline/filter/Dockerfile
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
    deduper:
        build:
            context: .
            dockerfile: ./house_listing_pipeline/deduper/Dockerfile
        depends_on:
            - redis
            - mongo
        environment:
            - REDIS_HOST=redis
            - MONGO_DB_HOST=mongo
    redis:
        image: redis:3.2-alpine
        volumes:
            - redis_data:/redis/data
    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db

volumes:
    redis_data:
    mongo_data:

