version: '3'
services:
    wechat:
        build:
            context: ./wechat_server
        depends_on:
            - redis
        environment:
            - REDIS_HOST=localhost
        ports:
            - "5001:5001"
    web:
        build:
            context: ./web_server
        ports:
            - "3001:3001"
    backend:
        build:
            context: ./backend_server 
        depends_on:
            - redis
        environment:
            - REDIS_HOST=localhost
        ports:
            - "4040:4040"
    pipeline:
        build:
            context: ./house_listing_pipeline
        depends_on:
            - redis
            - mongo
        environment:
            - REDIS_HOST=localhost
            - MONGO_DB_HOST=localhost
    redis:
        image: redis:3.2-alpine
        volumes:
            - redis_data:/redis/data
    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db

volumes:
    redis_data:
    mongo_data:

